### ISSUE TITLE
Correcciónes visuales del primer Milestone

### ISSUE THREAD

**Issue by cristianmarind** [ealejandro101/journal-research-client#15]
Proponemos los siguientes cambios con el fin de que los aprueben o los reformulen para incluirlos en el siguiente Milestone.

Para la página principal:
- [x] Cambiar el título de la página a Research-CFP.
- [x] En la página principal de Research CFP, en la primera sección: poner la imagen de fondo contenida en el div contenedor y que no se repita.
- [x] Que los enlaces del lado derecho del Header fijo sean con target: _blanck.
- [x] Quitar el espacio entre la barra de búsqueda y el botón buscar.

Para la página de búsqueda
- [x] Replantear la parte de los filtros para la versión móvil. Propuesta: la sección de los filtros en dispositivos móviles quedará en la parte izquierda oculta, con la posibilidad de mostrarlos y usarlos con un click
- [x] En el detalle de cada revista colocar la imagen en la misma columna pero arriba y que el texto rodee la imagen

**Comment by ealejandro101** [comment]
Por favor validar estos temas y si estan deacuerdo colocar un issue por cada uno
